### ISSUE TITLE
Create @types/use-position npm package to use the library also with Typescript

### ISSUE THREAD

**Issue by muscla87** [trekhleb/use-position#5]
I came across this simple but usefult module and I wanted to use it in my react project using Typescript. Unfortunately I cannot use it without any typescript types definition. Usually, for each nmp package there's a twin @types/module-name npm package which contains the module Typescript definition.

I made this module for you and just submitted a pull request on the main repository waiting for merging in the master branch and to be published in the NPM repository. You can follow pull request progress here: [DefinitelyTyped PR #41049](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41049)

I hope this will help your library to be user in many other Typescript projects!

I will close the Issue as soon as the final npm package is published.

**Comment by darbio** [comment]
This has been merged and can be closed.

**Comment by muscla87** [comment]
Closed
